config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('', RedirectView.as_view(url="/dashboard/"), name='home'),
    path('admin/', admin.site.urls),

    path('dashboard/', include(('paypal_ui.dashboard.urls', 'dashboard'), namespace='dashboard')),
]

paypal_ui/dashboard/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('active-plan/<str:plan_id>', views.active_plan, name='active_plan'),
    path('delete-plan/<str:plan_id>', views.delete_plan, name='delete_plan'),
    path('plan/<str:plan_id>', views.plan_detail, name='plan_detail'),
]

paypal_ui/dashboard/views.py
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import redirect
import json

from .paypay_api import paypal


def index(request):
    context = dict()
    if request.method == 'POST':
        kwargs = {
            'name': request.POST.get('name'),
            'description': request.POST.get('description'),
            'cancel_url': request.POST.get('cancel_url'),
            'return_url': request.POST.get('return_url'),
            'amount': request.POST.get('amount'),
            'frequency': request.POST.get('frequency'),
            'payment_name': request.POST.get('payment_name')
        }
        success, result = paypal.create_billing_plan(**kwargs)
        if success:
            messages.add_message(request, messages.SUCCESS, "Add billing plan success")
        else:
            messages.add_message(request, messages.ERROR, result)

    plans = paypal.get_billing_plans("ACTIVE")
    plans += paypal.get_billing_plans("CREATED")
    context["plans"] = plans
    return render(request, 'index.html', context)


def active_plan(request, plan_id):
    try:
        paypal.active_plan(plan_id)
        messages.add_message(request, messages.SUCCESS, "Active plan success")
    except Exception as e:
        messages.add_message(request, messages.ERROR, str(e))
    return redirect(reverse('dashboard:index'))


def delete_plan(request, plan_id):
    try:
        paypal.delete_plan(plan_id)
        messages.add_message(request, messages.SUCCESS, "Delete plan success")
    except Exception as e:
        messages.add_message(request, messages.ERROR, str(e))
    return redirect(reverse('dashboard:index'))


def plan_detail(request, plan_id):
    plan = paypal.get_plan(plan_id)
    context = {
        'plan': json.dumps(plan.to_dict(), indent=4)
    }
    return render(request, 'plan_detail.html', context)

paypal_ui/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Star Admin Free Bootstrap Admin Dashboard Template</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'star-admin/' %}vendors/iconfonts/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="{% static 'star-admin/' %}vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="{% static 'star-admin/' %}vendors/css/vendor.bundle.addons.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'star-admin/' %}css/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="{% static 'star-admin/' %}images/favicon.png"/>
</head>

<body>
<div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
            <a class="navbar-brand brand-logo" href="/">
                <img src="{% static 'star-admin/' %}images/logo.svg" alt="logo"/>
            </a>
            <a class="navbar-brand brand-logo-mini" href="/">
                <img src="{% static 'star-admin/' %}images/logo-mini.svg" alt="logo"/>
            </a>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-center">
            <ul class="navbar-nav navbar-nav-left header-links d-none d-md-flex">

            </ul>
            <ul class="navbar-nav navbar-nav-right">

                <li class="nav-item dropdown d-none d-xl-inline-block">
                    <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown"
                       aria-expanded="false">
                        <span class="profile-text">Hello, Richard V.Welsh !</span>
                        <img class="img-xs rounded-circle" src="{% static 'star-admin/' %}images/faces/face6.jpg" alt="Profile image">
                    </a>
                    <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
                        <a class="dropdown-item p-0">
                            <div class="d-flex border-bottom">
                                <div class="py-3 px-4 d-flex align-items-center justify-content-center">
                                    <i class="mdi mdi-bookmark-plus-outline mr-0 text-gray"></i>
                                </div>
                                <div class="py-3 px-4 d-flex align-items-center justify-content-center border-left border-right">
                                    <i class="mdi mdi-account-outline mr-0 text-gray"></i>
                                </div>
                                <div class="py-3 px-4 d-flex align-items-center justify-content-center">
                                    <i class="mdi mdi-alarm-check mr-0 text-gray"></i>
                                </div>
                            </div>
                        </a>
                        <a class="dropdown-item mt-2">
                            Manage Accounts
                        </a>
                        <a class="dropdown-item">
                            Change Password
                        </a>
                        <a class="dropdown-item">
                            Check Inbox
                        </a>
                        <a class="dropdown-item">
                            Sign Out
                        </a>
                    </div>
                </li>
            </ul>
            <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
                    data-toggle="offcanvas">
                <span class="mdi mdi-menu"></span>
            </button>
        </div>
    </nav>
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
            <ul class="nav">
                <li class="nav-item nav-profile">
                    <div class="nav-link">
                        <div class="user-wrapper">
                            <div class="profile-image">
                                <img src="{% static 'star-admin/' %}images/faces/face6.jpg" alt="profile image">
                            </div>
                            <div class="text-wrapper">
                                <p class="profile-name">Admin</p>
                                <div>
                                    <small class="designation text-muted">Admin</small>
                                    <span class="status-indicator online"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:index' %}">
                        <i class="menu-icon mdi mdi-television"></i>
                        <span class="menu-title">Dashboard</span>
                    </a>
                </li>
{#                <li class="nav-item">#}
{#                    <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false"#}
{#                       aria-controls="ui-basic">#}
{#                        <i class="menu-icon mdi mdi-content-copy"></i>#}
{#                        <span class="menu-title">Basic UI Elements</span>#}
{#                        <i class="menu-arrow"></i>#}
{#                    </a>#}
{#                    <div class="collapse" id="ui-basic">#}
{#                        <ul class="nav flex-column sub-menu">#}
{#                            <li class="nav-item">#}
{#                                <a class="nav-link" href="pages/ui-features/buttons.html">Buttons</a>#}
{#                            </li>#}
{#                            <li class="nav-item">#}
{#                                <a class="nav-link" href="pages/ui-features/typography.html">Typography</a>#}
{#                            </li>#}
{#                        </ul>#}
{#                    </div>#}
{#                </li>#}

            </ul>
        </nav>
        <!-- partial -->
        <div class="main-panel">

            <div class="content-wrapper">
                {% if messages %}
                    <div class="row" style="margin-bottom: 10px">
                        <div class="col-md-12">
                            {% for message in messages %}
                                {% if message.tags == 'success' %}
                                    <div class="alert alert-success alert-dismissible" role="alert">
                                        <button type="button" class="close" data-dismiss="alert"
                                                aria-label="Close"><span
                                                aria-hidden="true">&times;</span></button>
                                        <strong>Success!</strong> {{ message|safe }}
                                    </div>
                                {% elif message.tags == 'error' %}
                                    <div class="alert alert-danger alert-dismissible" role="alert">
                                        <button type="button" class="close" data-dismiss="alert"
                                                aria-label="Close"><span
                                                aria-hidden="true">&times;</span></button>
                                        <strong>Error!</strong> {{ message|safe }}
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}

                {% block content %}

                {% endblock %}
            </div>

            <!-- partial:partials/_footer.html -->
            <footer class="footer">
                <div class="container-fluid clearfix">
            <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2018
              <a href="http://www.bootstrapdash.com/" target="_blank">Bootstrapdash</a>. All rights reserved.</span>
                    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with
              <i class="mdi mdi-heart text-danger"></i>
            </span>
                </div>
            </footer>
            <!-- partial -->
        </div>
        <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
</div>
<!-- container-scroller -->

<!-- plugins:js -->
<script src="{% static 'star-admin/' %}vendors/js/vendor.bundle.base.js"></script>
<script src="{% static 'star-admin/' %}vendors/js/vendor.bundle.addons.js"></script>
<!-- endinject -->
<!-- Plugin js for this page-->
<!-- End plugin js for this page-->
<!-- inject:js -->
<script src="{% static 'star-admin/' %}js/off-canvas.js"></script>
<script src="{% static 'star-admin/' %}js/misc.js"></script>
<!-- endinject -->
<!-- Custom js for this page-->
<script src="{% static 'star-admin/' %}js/dashboard.js"></script>
<!-- End custom js for this page-->
</body>

</html>

paypal_ui/templates/index.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">

            <div class="card">
                <div class="card-header clearfix">
                    <h4 class="float-left">List Billing Plans</h4>
                    <div class="float-right">
                        <button class="btn btn-primary" data-toggle="modal" data-target="#add-plan">Add Plan</button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>State</th>
                                <th>Description</th>
                                <th>Create time</th>
                                {#                                <th>Update time</th>#}
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for plan in plans %}
                                <tr>
                                    <td><a href="{% url 'dashboard:plan_detail' plan.id %}">{{ plan.id }}</a></td>
                                    <td>{{ plan.name }}</td>
                                    <td><lable class="badge badge-success">{{ plan.state }}</lable></td>
                                    <td>{{ plan.description }}</td>
                                    <td>{{ plan.create_time }}</td>
                                    {#                                    <td>{{ plan.update_time }}</td>#}
                                    <td>
                                        <a class="btn btn-danger btn-sm"
                                           href="{% url 'dashboard:delete_plan' plan.id %}">Delete</a>

                                        {% if plan.state == 'CREATED' %}
                                            <a class="btn btn-info btn-sm" href="{% url 'dashboard:active_plan' plan.id %}">Active</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Modal -->
    <div class="modal fade" id="add-plan" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Billing Plan Information</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Name</label>
                            <div class="col-sm-9">
                                <input type="text" name="name" class="form-control" autocomplete="off">
                            </div>
                        </div>
                        <div class="form-group row">

                            <label for="" class="col-sm-3 col-form-label">Description</label>
                            <div class="col-sm-9">
                                <input type="text" name="description" class="form-control" autocomplete="off">
                            </div>
                        </div>

                        <h5>Merchant preferences</h5>
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Cancel Url</label>
                            <div class="col-sm-9">
                                <input type="text" name="cancel_url" class="form-control" autocomplete="off">
                            </div>
                        </div>
                        <div class="form-group row">

                            <label for="" class="col-sm-3 col-form-label">Return Url</label>
                            <div class="col-sm-9">
                                <input type="text" name="return_url" class="form-control" autocomplete="off">
                            </div>
                        </div>

                        <h5>Payment definitions</h5>
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Payment Name</label>
                            <div class="col-sm-9">
                                <input type="text" name="payment_name" class="form-control" autocomplete="off">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Amount ($)</label>
                            <div class="col-sm-9">
                                <input type="text" name="amount" class="form-control" autocomplete="off">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Frequency</label>
                            <div class="col-sm-9">
                                <select name="frequency" class="form-control">
                                    <option value="DAY">DAY</option>
                                    <option value="WEEK">WEEK</option>
                                    <option value="MONTH">MONTH</option>
                                    <option value="YEAR">YEAR</option>
                                </select>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-success mr-2">Submit</button>
                        <button class="btn btn-light" data-dismiss="modal">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

paypal_ui/templates/plan_detail.html
{% extends 'base.html' %}

{% block content %}
    <h4>Billing Plan Information</h4>
<pre>
    {{ plan }}
</pre>
{% endblock %}